const resultCode = {

    CODE_SUCCESS: 'SUCCESS',
    CODE_ERROR: 'ERR_SYSTEM',
    CODE_ERROR_SQL: 'ERR_SQL_QUERY',
    CODE_ERROR_VALIDATE: 'ERR_VALIDATE',
    CODE_ERROR_AUTHENTICATION: 'ERR_AUTHENTICATION',
    CODE_ERROR_NOTFOUND: 'ERR_DATA_NOTFOUND',
    CODE_ERROR_TOKEN: 'ERR_TOKEN',
};

export default resultCode;